version: '3'

services:
  mysql1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress1
    volumes:
      - db1:/var/lib/mysql
  mysql2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress2
    volumes:
      - db2:/var/lib/mysql
  wordpress1:
    image: wordpress
    ports:
      - "8000:80"
    depends_on:
      - mysql1
    environment:
      WORDPRESS_DB_HOST: mysql1
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress1
  wordpress2:
    image: wordpress
    ports:
      - "8001:80"
    depends_on:
      - mysql2
    environment:
      WORDPRESS_DB_HOST: mysql2
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress2

volumes:
  db1:
  db2:
